const assert = require('assert');
const Tool = require('./core');
const english = Tool.estimate('Hello world. This is a rough size estimate.');
const cjk = Tool.estimate('你好世界你好世界');
const emoji = Tool.estimate('😀😀😀😀');
assert.ok(english.range.low <= english.estimatedTokens && english.estimatedTokens <= english.range.high);
assert.ok(cjk.estimatedTokens >= 8);
assert.ok(emoji.estimatedTokens >= 8);
assert.strictEqual('pricingEstimates' in english, false);
assert.ok(/Exact counts require/.test(english.note));
console.log('ok, honest token range assertions passed');
